"""Atualização de tabelas, incluindo itens do pedido

Revision ID: c110fccd4ccc
Revises: 59c58b2535e0
Create Date: 2025-06-25 18:45:26.279293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c110fccd4ccc'
down_revision: Union[str, None] = '59c58b2535e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
